package GUI.Medico;

import GUI.Gestor.TableAdaptor;
import clases.Medico;
import clases.PdfConversor;
import clases.Selector;
import com.itextpdf.text.DocumentException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pablo
 */
public class ModificarFichaSeleccionada extends javax.swing.JPanel {

	/**
	 * Creates new form mostrarPacientesMedico
	 */
	private Medico medico;
	private String codFicha;
	private String hora;
	private String dia;
	private String comentario;
	private String nombre = null;

	public ModificarFichaSeleccionada(Medico medico, String nombre, String codFicha, String hora, String dia, String comentario) {
		this.medico = medico;
		this.codFicha = codFicha;
		this.hora = hora;
		this.dia = dia;
		this.comentario = comentario;
		this.nombre = nombre;

		this.setBackground(new java.awt.Color(150, 190, 230));

		initComponents();
		initVentana();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DiaHora = new javax.swing.JLabel();
        campoDiaHora = new javax.swing.JLabel();
        labelFicha = new javax.swing.JLabel();
        campoCodFicha = new javax.swing.JLabel();
        labelComentario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaComentario = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaComentario1 = new javax.swing.JTextArea();
        Guardar = new javax.swing.JButton();
        fichaPDF = new javax.swing.JButton();

        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        DiaHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DiaHora.setText("Dia");

        campoDiaHora.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        campoDiaHora.setForeground(new java.awt.Color(0, 51, 102));
        campoDiaHora.setText("");

        labelFicha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelFicha.setText("Ficha");

        campoCodFicha.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        campoCodFicha.setForeground(new java.awt.Color(0, 51, 102));
        campoCodFicha.setText("");

        labelComentario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelComentario.setText("Comentario:");

        jTextAreaComentario.setColumns(20);
        jTextAreaComentario.setRows(5);
        jTextAreaComentario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextAreaComentarioKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaComentario);

        jTextAreaComentario1.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaComentario1.setColumns(20);
        jTextAreaComentario1.setRows(5);
        jScrollPane2.setViewportView(jTextAreaComentario1);

        Guardar.setText("Guardar");
        Guardar.setEnabled(false);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        fichaPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pdf_icon.png"))); // NOI18N
        fichaPDF.setText("Guardar Ficha en PDF");
        fichaPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoCodFicha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DiaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(campoDiaHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(241, 241, 241))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(fichaPDF)))
                        .addContainerGap(224, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDiaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCodFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fichaPDF))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
		// TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
		try {
			int confirmacion = 0;
			confirmacion = ventanaConfirmar();
			if (confirmacion == 1) {
				String comentarioNuevo = jTextAreaComentario.getText();
				jTextAreaComentario.setText("");
				medico.updateFicha(this.comentario, comentarioNuevo, codFicha);
				recargarVentana();
			} else {
				initVentana();
			}
		} catch (SQLException ex) {
			Logger.getLogger(ModificarFichaSeleccionada.class.getName()).log(Level.SEVERE, null, ex);
		}

    }//GEN-LAST:event_GuardarActionPerformed

    private void jTextAreaComentarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaComentarioKeyTyped
		Guardar.setEnabled(true);
    }//GEN-LAST:event_jTextAreaComentarioKeyTyped

    private void fichaPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaPDFActionPerformed
		seleccionHubicacion();
    }//GEN-LAST:event_fichaPDFActionPerformed
	private void initVentana() {
		campoDiaHora.setText(dia + "  " + hora);
		campoCodFicha.setText(codFicha);
		jTextAreaComentario1.setText(comentario);
		Guardar.setEnabled(false);
		jTextAreaComentario.setText(null);
	}

	private void recargarVentana() throws SQLException {
		ArrayList<String> ficha = medico.cargarFicha(codFicha);
		this.codFicha = ficha.get(0);
		this.comentario = ficha.get(1);
		this.dia = ficha.get(2);
		this.hora = ficha.get(3);
		initVentana();

	}

	private int ventanaConfirmar() {
		Object[] options = {"Cancelar", "Guardar"};
		return JOptionPane.showOptionDialog(this, "Se van a guardar los cambios, ¿Desea confirmar la operación?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
	}

	private void seleccionHubicacion() {
		Selector explorador = new Selector();
		int seleccion = explorador.opcionMarcada();

		switch (seleccion) {
			case JFileChooser.APPROVE_OPTION:
				guardarPdf(explorador.retornarDirectorioElegido());
				break;

			case JFileChooser.CANCEL_OPTION:
				break;

			case JFileChooser.ERROR_OPTION:
				break;
		}
	}

	private void guardarPdf(String directorio) {
		try {
			PdfConversor conversor = new PdfConversor(codFicha, nombre, hora, dia, comentario, medico.getN_colegiado(), directorio);
			conversor.getPdfFicha();
			JOptionPane.showMessageDialog(this, "¡Se ha generado tu hoja PDF!",
					"RESULTADO", JOptionPane.INFORMATION_MESSAGE);
		} catch (DocumentException ex) {
			Logger.getLogger(mostrarCitasMedico.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, "Se ha producido un error al generar un documento: " + ex,
					"ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiaHora;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel campoCodFicha;
    private javax.swing.JLabel campoDiaHora;
    private javax.swing.JButton fichaPDF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaComentario;
    private javax.swing.JTextArea jTextAreaComentario1;
    private javax.swing.JLabel labelComentario;
    private javax.swing.JLabel labelFicha;
    // End of variables declaration//GEN-END:variables

}
