package GUI.Gestor.Paciente;

import clases.Gestor;
import clases.Paciente;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Juan
 */
public class PedirCita extends javax.swing.JPanel {

	private Gestor gestor;
	private Paciente paciente;

	public PedirCita(Gestor gestor, Paciente paciente) {
		initComponents();
		this.gestor = gestor;
		this.paciente = paciente;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mostrarDatos = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelMedico = new javax.swing.JLabel();
        Especialidad = new javax.swing.JLabel();
        desplegableEspecialidad = new javax.swing.JComboBox();
        desplegableMedico = new javax.swing.JComboBox();
        labelDia = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        buttonPedirCita = new javax.swing.JButton();
        desplegableHoras = new javax.swing.JComboBox();
        desplegableTurno = new javax.swing.JComboBox();
        Turno = new javax.swing.JLabel();
        buttonCargar = new javax.swing.JButton();
        calendario = new com.toedter.calendar.JCalendar();

        jLabel1.setText("jLabel1");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Pedir cita paciente");
        labelTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelMedico.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelMedico.setText("Medico");

        Especialidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Especialidad.setText("Especialidad");

        desplegableEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableEspecialidadActionPerformed(evt);
            }
        });

        labelDia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelDia.setText("Dia");

        labelHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelHora.setText("Hora");

        buttonPedirCita.setText("Pedir cita");
        buttonPedirCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPedirCitaActionPerformed(evt);
            }
        });

        Turno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Turno.setText("Turno");

        buttonCargar.setText("Cargar");
        buttonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mostrarDatosLayout = new javax.swing.GroupLayout(mostrarDatos);
        mostrarDatos.setLayout(mostrarDatosLayout);
        mostrarDatosLayout.setHorizontalGroup(
            mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mostrarDatosLayout.createSequentialGroup()
                        .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mostrarDatosLayout.createSequentialGroup()
                                .addComponent(buttonCargar)
                                .addGap(141, 141, 141)
                                .addComponent(buttonPedirCita, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mostrarDatosLayout.createSequentialGroup()
                                    .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(desplegableHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mostrarDatosLayout.createSequentialGroup()
                                    .addComponent(labelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(desplegableMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mostrarDatosLayout.createSequentialGroup()
                                    .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(desplegableTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mostrarDatosLayout.createSequentialGroup()
                                    .addComponent(Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)
                                    .addComponent(desplegableEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(labelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mostrarDatosLayout.setVerticalGroup(
            mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mostrarDatosLayout.createSequentialGroup()
                        .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desplegableEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Turno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desplegableTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(desplegableMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desplegableHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mostrarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCargar)
                    .addComponent(buttonPedirCita, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mostrarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void cargarDatos() throws SQLException {
		desplegableEspecialidad.setModel(new DefaultComboBoxModel(gestor.getEspecialidades()));
	}

    private void buttonPedirCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPedirCitaActionPerformed

    }//GEN-LAST:event_buttonPedirCitaActionPerformed

    private void buttonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCargarActionPerformed
		try {
			cargarDatos();
		} catch (SQLException ex) {
			Logger.getLogger(PedirCita.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_buttonCargarActionPerformed

	private String diaSemana(String dia) {
		return dia;
	}

	private String cogerDia(String diaNum) {
		String diaTexto = "";
		switch (diaNum) {
			case "1":
				diaTexto = "Lunes";
				break;
			case "2":
				diaTexto = "Martes";
				break;
			case "3":
				diaTexto = "Miercoles";
				break;
			case "4":
				diaTexto = "Jueves";
				break;
			case "5":
				diaTexto = "Viernes";
				break;
			case "6":
				diaTexto = "Sabado";
				break;
			case "7":
				diaTexto = "Domingo";
				break;
		}
		return diaTexto;
	}

    private void desplegableEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableEspecialidadActionPerformed
		SimpleDateFormat formato = new SimpleDateFormat("yy-MM-dd");
		SimpleDateFormat diaSemanas = new SimpleDateFormat("u");

		System.out.println(diaSemanas.format(calendario.getDate()));
		System.out.println(formato.format(calendario.getDate()));
		
		String especialidad = (String) desplegableEspecialidad.getSelectedItem();
		String fecha = formato.format(calendario.getDate());
		String diaSemana = cogerDia(diaSemanas.format(calendario.getDate()));
		System.out.println(calendario.getDate());
		System.out.println(diaSemana);
		try {
			desplegableTurno.setModel(new DefaultComboBoxModel(gestor.getHorarioEspecialidadByDay(especialidad, diaSemana)));
			String turno = (String) desplegableTurno.getSelectedItem();
			//desplegableMedico.setModel(new DefaultComboBoxModel((String) gestor.mostrarMedicosByHorarioEspecialidad(especialidad, turno)));
		} catch (SQLException ex) {
			Logger.getLogger(PedirCita.class.getName()).log(Level.SEVERE, null, ex);
		}

    }//GEN-LAST:event_desplegableEspecialidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Especialidad;
    private javax.swing.JLabel Turno;
    private javax.swing.JButton buttonCargar;
    private javax.swing.JButton buttonPedirCita;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JComboBox desplegableEspecialidad;
    private javax.swing.JComboBox desplegableHoras;
    private javax.swing.JComboBox desplegableMedico;
    private javax.swing.JComboBox desplegableTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelMedico;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel mostrarDatos;
    // End of variables declaration//GEN-END:variables
}
