/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Conexion;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class MenuAdmin extends javax.swing.JPanel {

	private Conexion con;

	public MenuAdmin(Conexion con) {
		initComponents();
		this.con = con;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesAdmin = new javax.swing.JPanel();
        construirDatabase = new javax.swing.JButton();
        destruirDatabase = new javax.swing.JButton();

        construirDatabase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        construirDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_pequeño.png"))); // NOI18N
        construirDatabase.setText("Construir centromedico");
        construirDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                construirDatabaseActionPerformed(evt);
            }
        });

        destruirDatabase.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        destruirDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo_pequeño.png"))); // NOI18N
        destruirDatabase.setText("Destruir centromedico");
        destruirDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destruirDatabaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesAdminLayout = new javax.swing.GroupLayout(opcionesAdmin);
        opcionesAdmin.setLayout(opcionesAdminLayout);
        opcionesAdminLayout.setHorizontalGroup(
            opcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAdminLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(construirDatabase)
                .addGap(395, 395, 395)
                .addComponent(destruirDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        opcionesAdminLayout.setVerticalGroup(
            opcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesAdminLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(opcionesAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destruirDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(construirDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionesAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionesAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void construirDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_construirDatabaseActionPerformed
		try {
			if (con.existeBD()){
				JOptionPane.showMessageDialog(this, "Ya existe la base de datos centromedico", "Error", JOptionPane.ERROR_MESSAGE);
			} else {
				con.crearBD();
				JOptionPane.showMessageDialog(this, "Se ha construido correctamente centromedico", "Exito", JOptionPane.PLAIN_MESSAGE);
			}
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(this, "Ya esta creada: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
			Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_construirDatabaseActionPerformed

    private void destruirDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destruirDatabaseActionPerformed
        try {
			if (!con.existeBD()){
				JOptionPane.showMessageDialog(this, "No existe la base de datos centromedico", "Error", JOptionPane.ERROR_MESSAGE);
			} else {
				con.destruirBD();
				JOptionPane.showMessageDialog(this, "Se ha destruido correctamente centromedico", "Exito", JOptionPane.PLAIN_MESSAGE);
			}
		} catch (SQLException ex) {
			JOptionPane.showMessageDialog(this, "Ya esta creada: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
			Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_destruirDatabaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton construirDatabase;
    private javax.swing.JButton destruirDatabase;
    private javax.swing.JPanel opcionesAdmin;
    // End of variables declaration//GEN-END:variables
}
